package com.example.demo.entity;

public class SysRoleMenuEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.menuId
     *
     * @mbggenerated
     */
    private Long menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.id
     *
     * @return the value of sys_role_menu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.id
     *
     * @param id the value for sys_role_menu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.roleId
     *
     * @return the value of sys_role_menu.roleId
     *
     * @mbggenerated
     * @param roleId
     */
    public Long getRoleid(Long roleId) {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.roleId
     *
     * @param roleid the value for sys_role_menu.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.menuId
     *
     * @return the value of sys_role_menu.menuId
     *
     * @mbggenerated
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.menuId
     *
     * @param menuid the value for sys_role_menu.menuId
     *
     * @mbggenerated
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }
}