package com.example.demo.entity;

public class SysUserRoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.id
     *
     * @return the value of sys_userrole.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.id
     *
     * @param id the value for sys_userrole.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.userId
     *
     * @return the value of sys_userrole.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.userId
     *
     * @param userid the value for sys_userrole.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.roleId
     *
     * @return the value of sys_userrole.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.roleId
     *
     * @param roleid the value for sys_userrole.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}