package com.example.demo.mapper;

import com.example.demo.entity.SysUserRoleEntity;
import java.util.List;

public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    int deleteByuserid(Long userid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrole
     *
     * @mbggenerated
     */
    int insert(SysUserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrole
     *
     * @mbggenerated
     */
    SysUserRoleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrole
     *
     * @mbggenerated
     */
    List<SysUserRoleEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserRoleEntity record);
}